---
name: Math-Geometry-Planar-Offset
version: 1.04
author: []
abstract: Calculate offset polygons
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
  YAML: 0
provides:
  Math::Geometry::Planar::Offset:
    file: lib/Math/Geometry/Planar/Offset.pm
    version: 1.04
generated_by: Module::Build version 0.28
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
